export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ENROLLED_CLASSES = 'GET_ENROLLED_CLASSES';
export const GET_UNENROLLED_CLASSES = 'GET_UNENROLLED_CLASSES';
export const LOADING = 'LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const ENROLL_CLASS = 'ENROLL_CLASS';
export const UNENROLL_CLASS = 'UNENROLL_CLASS';

